### ISSUE TITLE
Add more items to headers list

### ISSUE THREAD

**Issue by gisostallenberg** [ralouphie/getallheaders#1]
As you can see in https://github.com/symfony/http-foundation/blob/6edfe4a63b1f5c0a3d0c6190998c9089784ea883/ServerBag.php there are more headers that should be returned

**Comment by ralouphie** [comment]
Thanks for the feedback! I've updated the polyfill to include more headers from various PHP-set `$_SERVER` values.

**Comment by gisostallenberg** [comment]
:+1:
